import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppWrapper } from "@/context";
import AppPage from "./App";
import AuthProvider from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Morocco Marvel Travels",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="./favicon.ico" sizes="any" />
      <body className={inter.className}>
        <AuthProvider>
          <AppWrapper>
            <AppPage>{children}</AppPage>
          </AppWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
